# Use this file to configure the Overcommit hooks you wish to use
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/brigade/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/brigade/overcommit#configuration

PreCommit:
  Scalastyle:
    enabled: true
    on_warn: fail
    flags: ['-c', '/home/eppie/Downloads/scalastyle_config.xml']

  TrailingWhitespace:
    enabled: true

  AuthorEmail:
    enabled: true

  Brakeman:
    enabled: true

  BrokenSymlinks:
    enabled: true

  CaseConflicts:
    enabled: true

  EsLint:
    enabled: true

  GoLint:
    enabled: true

  Hlint:
    enabled: true

  JavaCheckstyle:
    enabled: true

  JsHint:
    enabled: true
